# Generated by Django 2.0.2 on 2018-03-28 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0028_auto_20180326_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackEntered', models.TextField(max_length=300)),
                ('dateFeedbackEntered', models.DateField()),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.BuyerDetails')),
                ('oid', models.ForeignKey(db_column='oid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.OrderDetails')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProductDetails')),
            ],
            options={
                'db_table': 'feedback_details',
                'managed': True,
            },
        ),
    ]
