# Generated by Django 2.0.2 on 2018-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks_app', '0002_feedbackdetails_feedbackrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdetails',
            name='feedbackRating',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0'),
        ),
    ]
