# Generated by Django 2.0.2 on 2018-03-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks_app', '0005_auto_20180328_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='pid',
        ),
        migrations.DeleteModel(
            name='FeedbackDetails',
        ),
    ]
