# Generated by Django 2.0.2 on 2018-03-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_productmain'),
        ('feedbacks_app', '0007_feedbackdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feedback_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(max_length=500)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProductMain')),
            ],
        ),
    ]
