# Generated by Django 2.0.2 on 2018-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks_app', '0008_feedbacks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='pid',
        ),
        migrations.DeleteModel(
            name='Feedbacks',
        ),
    ]
