# Generated by Django 2.0.2 on 2018-04-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks_app', '0011_auto_20180410_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbacks_table',
            old_name='feedback',
            new_name='feedback_entered',
        ),
        migrations.RenameField(
            model_name='feedbacks_table',
            old_name='feedback_date',
            new_name='feedbackdate',
        ),
        migrations.RenameField(
            model_name='feedbacks_table',
            old_name='pid',
            new_name='pid_seller',
        ),
    ]
