# Generated by Django 2.0.2 on 2018-04-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20180422_0045'),
        ('feedbacks_app', '0012_auto_20180410_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('feedback_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(max_length=500)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Products')),
            ],
        ),
    ]
