# Generated by Django 2.0.2 on 2018-03-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDetails',
            fields=[
                ('bid', models.TextField(primary_key=True, serialize=False)),
                ('bname', models.TextField()),
            ],
            options={
                'db_table': 'buyer_details',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('oid', models.TextField(primary_key=True, serialize=False)),
                ('exp_shipment', models.DateField()),
                ('exp_delivery', models.DateField()),
                ('actual_shipment', models.DateField()),
                ('actual_delivery', models.DateField()),
                ('status', models.TextField()),
                ('bid', models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.BuyerDetails')),
            ],
            options={
                'db_table': 'order_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('pid', models.TextField(primary_key=True, serialize=False)),
                ('pname', models.TextField()),
                ('sid', models.TextField()),
            ],
            options={
                'db_table': 'product_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('sid', models.TextField(primary_key=True, serialize=False)),
                ('sname', models.TextField()),
            ],
            options={
                'db_table': 'seller_details',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ProductDetails'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.SellerDetails'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetails',
            unique_together={('oid', 'pid', 'sid', 'bid')},
        ),
    ]
