# Generated by Django 2.0.2 on 2018-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180315_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='actual_delivery',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='actual_shipment',
            field=models.DateField(null=True),
        ),
    ]
