# Generated by Django 2.0.2 on 2018-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180315_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='tid',
            field=models.TextField(null=True),
        ),
    ]
