# Generated by Django 2.0.2 on 2018-03-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_orderdetails_tid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='oid',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='tid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
