# Generated by Django 2.0.2 on 2018-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180316_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='tid',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
