# Generated by Django 2.0.2 on 2018-03-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180316_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='tid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
