# Generated by Django 2.0.2 on 2018-03-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180316_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.SellerDetails'),
        ),
    ]
