# Generated by Django 2.0.2 on 2018-03-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180316_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitValueDetails',
            fields=[
                ('ttid', models.AutoField(primary_key=True, serialize=False)),
                ('late_shipment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('on_time_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('hit_to_success_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.SellerDetails')),
            ],
            options={
                'db_table': 'traits_value_details',
                'managed': True,
            },
        ),
    ]
