# Generated by Django 2.0.2 on 2018-03-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180319_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='bid',
            field=models.ForeignKey(db_column='bid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.BuyerDetails'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='pid',
            field=models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.ProductDetails'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='sid',
            field=models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails'),
        ),
    ]
