# Generated by Django 2.0.2 on 2018-03-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180320_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerdetails',
            name='bid',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buyerdetails',
            name='bname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='oid',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='pid',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='pname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='sid',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerdetails',
            name='sname',
            field=models.CharField(max_length=25),
        ),
    ]
