# Generated by Django 2.0.2 on 2018-03-20 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180320_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('sid', models.OneToOneField(db_column='sid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dashboard.SellerDetails')),
                ('cid', models.TextField()),
            ],
            options={
                'db_table': 'cancellation',
                'managed': True,
            },
        ),
    ]
