# Generated by Django 2.0.2 on 2018-03-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_cancellation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancellation',
            name='sid',
        ),
        migrations.DeleteModel(
            name='Cancellation',
        ),
    ]
