# Generated by Django 2.0.2 on 2018-03-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180320_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traitvaluedetails',
            name='sid',
        ),
        migrations.DeleteModel(
            name='TraitValueDetails',
        ),
    ]
