# Generated by Django 2.0.2 on 2018-03-20 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20180320_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitValueDetails',
            fields=[
                ('tid', models.TextField(primary_key=True, serialize=False)),
                ('late_shipment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('on_time_delivery', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('hit_to_success_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('return_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('sid', models.ForeignKey(db_column='sid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails')),
            ],
            options={
                'db_table': 'traits_value_details',
                'managed': True,
            },
        ),
    ]
