# Generated by Django 2.0.2 on 2018-03-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_traitvaluedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitvaluedetails',
            name='overall_perf_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
