# Generated by Django 2.0.2 on 2018-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_productdetails_no_of_hits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='no_of_hits',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
