# Generated by Django 2.0.2 on 2018-03-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20180321_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='no_of_hits',
            field=models.IntegerField(default=0),
        ),
    ]
