# Generated by Django 2.0.2 on 2018-03-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20180321_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitvaluedetails',
            name='recommendations_lateShipmentRate',
            field=models.TextField(default='abc', max_length=100),
        ),
    ]
