# Generated by Django 2.0.2 on 2018-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20180321_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitvaluedetails',
            name='late_shipment_rate_recommendation',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
