# Generated by Django 2.0.2 on 2018-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_traitvaluedetails_late_shipment_rate_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitvaluedetails',
            name='hit_to_success_recommendation',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='traitvaluedetails',
            name='on_time_delivery_recommendation',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='traitvaluedetails',
            name='return_rate_recommendation',
            field=models.TextField(default=None, max_length=100),
        ),
    ]
