# Generated by Django 2.0.2 on 2018-03-25 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20180326_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traitvaluedetails',
            name='recommendations_returnRate',
        ),
        migrations.RemoveField(
            model_name='traitvaluedetails',
            name='return_rate',
        ),
    ]
