# Generated by Django 2.0.2 on 2018-03-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20180330_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20)),
                ('cid', models.CharField(max_length=20)),
                ('sid', models.CharField(max_length=10)),
                ('prod_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('launch_date', models.DateField()),
                ('score', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
