# Generated by Django 2.0.2 on 2018-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_productmain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmain',
            name='pid',
        ),
        migrations.AlterField(
            model_name='productmain',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
