# Generated by Django 2.0.2 on 2018-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_auto_20180331_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cname', models.TextField(max_length=30)),
                ('subCategory', models.TextField(max_length=30)),
                ('subCategoryCount', models.IntegerField()),
            ],
        ),
    ]
