# Generated by Django 2.0.2 on 2018-03-31 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmain',
            name='cid',
        ),
    ]
