# Generated by Django 2.0.2 on 2018-03-31 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_remove_productmain_cid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductMain',
        ),
    ]
