# Generated by Django 2.0.2 on 2018-03-31 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_delete_productmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMain',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=10)),
                ('prod_count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('launch_date', models.DateField()),
                ('score', models.IntegerField()),
                ('inventory', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
            ],
        ),
    ]
