# Generated by Django 2.0.2 on 2018-03-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_productmain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_date',
            field=models.DateField(),
        ),
    ]
