# Generated by Django 2.0.2 on 2018-03-31 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20180401_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='traitvaluedetails',
            name='negative_feedbacks',
            field=models.TextField(default='abc', max_length=500),
        ),
        migrations.AddField(
            model_name='traitvaluedetails',
            name='positive_feedbacks',
            field=models.TextField(default='abc', max_length=500),
        ),
    ]
