# Generated by Django 2.0.2 on 2018-04-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20180401_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmain',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SellerDetails'),
        ),
    ]
