# Generated by Django 2.0.2 on 2018-04-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20180403_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmain',
            name='sid',
            field=models.CharField(max_length=10),
        ),
    ]
