# Generated by Django 2.0.2 on 2018-04-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20180403_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmain',
            old_name='cid',
            new_name='sub_cid',
        ),
    ]
