# Generated by Django 2.0.2 on 2018-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20180403_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traitvaluedetails',
            name='negative_feedbacks',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='traitvaluedetails',
            name='positive_feedbacks',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='traitvaluedetails',
            name='recommendations_HitToSucessRatio',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traitvaluedetails',
            name='recommendations_lateShipmentRate',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traitvaluedetails',
            name='recommendations_onTimeDeliery',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='traitvaluedetails',
            name='recommendations_returnRate',
            field=models.TextField(max_length=100),
        ),
    ]
