# Generated by Django 2.0.2 on 2018-04-21 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_buyer_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('subcategory_name', models.TextField(max_length=30)),
                ('subcategory_sale_count', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
            ],
        ),
    ]
