# Generated by Django 2.0.2 on 2018-04-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_categories_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categories'),
        ),
    ]
