# Generated by Django 2.0.2 on 2018-04-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20180422_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='cid',
            new_name='category_id',
        ),
    ]
