# Generated by Django 2.0.2 on 2018-04-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Seller'),
        ),
    ]
