# Generated by Django 2.0.2 on 2018-04-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_auto_20180422_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Subcategories'),
        ),
    ]
