# Generated by Django 2.0.2 on 2018-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20180422_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='subcategory_id',
            field=models.TextField(max_length=50),
        ),
    ]
