# Generated by Django 2.0.2 on 2018-04-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_auto_20180422_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('OD', 'ontime_delivery'), ('LD', 'late_delivery'), ('C', 'cancelled'), ('R', 'returned')], max_length=2),
        ),
    ]
