# Generated by Django 2.0.2 on 2018-04-22 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_auto_20180422_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='tid',
            new_name='id',
        ),
    ]
