# Generated by Django 2.0.2 on 2018-04-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20180422_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hits',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hit_date', models.DateField()),
                ('hits', models.IntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Products')),
            ],
        ),
    ]
