# Generated by Django 2.0.2 on 2018-04-22 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0057_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traitvaluedetails',
            name='sid',
        ),
        migrations.DeleteModel(
            name='TraitValueDetails',
        ),
    ]
